# .devcontainer/frontend/docker-compose.yml
services:
  frontend:
    build:
      context: ../..
      dockerfile: .devcontainer/frontend/Dockerfile
    volumes:
      - ../../frontend:/workspaces/frontend:cached
      - node_modules_frontend:/workspaces/frontend/node_modules
      - angular_cache:/workspaces/frontend/.angular
    command: sleep infinity
    stdin_open: true
    tty: true
    ports:
      - "4200:4200"
    networks:
      - dev_network_external
      
# --- Definición de Redes y Volúmenes ---
networks:
  # CLAVE: Declara que la red es externa, apuntando a la que creamos.
  dev_network_external:
    name: dev_raffles
    external: true

volumes:
  node_modules_frontend:
  angular_cache: